spring.application.name=helpflow-canva-backend
spring.profiles.active=dev
server.port=10170

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/helpflow_db
spring.datasource.username=root
spring.datasource.password=150396ju
spring.datasource.driver-class-name=

# Redis cache configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000

# JPA (Hibernate) Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Connection Pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

